# Generated by Django 3.1 on 2020-08-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmePequenosNegocios', '0003_auto_20200822_1750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductiImage',
            new_name='ProductImage',
        ),
    ]
