# Generated by Django 3.1 on 2020-08-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmePequenosNegocios', '0007_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cashback',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
