# Generated by Django 3.1 on 2020-08-24 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AmePequenosNegocios', '0011_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CPF',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=1235),
            preserve_default=False,
        ),
    ]
